matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      #services: docker
language: generic
os:
  - linux
  - osx

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1

#node_js:
#  - '7'

branches:
  only:
    - master

script: ./tools/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
