version: 0.1.{build}
build: off
os: unstable

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  matrix:
    - nodejs_version: '8'
  GH_TOKEN:
    secure: dpurh8s4ulOTEbFB2xWmG9u2zAuPpbLce9Kdc+QzGzixr//goftP0s/mbzBvEuKk

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - git reset --hard HEAD
  - npm install
  - set PATH=%APPDATA%\npm;%PATH%
  #- npm prune

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - node_modules/.bin/mocha --recursive

skip_commits:
  message: /\[ci\s+skip\]/

build_script:
  - node --version
  - npm --version
  - npm run dist
