#version: 0.1.{build}
#build: off
os: unstable

platform:
  - x64

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  matrix:
    - nodejs_version: '8'
  GH_TOKEN:
    secure: 'hWq+UymjZYRfgJPKsRQ8bBFwkcMHpLglVbYe0FH2w0zdQ6/8Dp3mo/19RFKIpZkU'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - git reset --hard HEAD
  - yarn install
  - set PATH=%APPDATA%\npm;%PATH%

matrix:
  fast_finish: true

test: off

#test_script:
#  - node --version

skip_commits:
  message: /\[ci\s+skip\]/

build_script:
  - node --version
  - yarn run dist

only_commits:
  message: /build/

# deploy:
#   - provider: GitHub
#     artifact: /*.exe/
#     draft: true
#     force_update: true
