# Site settings
title: Before Dawn -- Screensaver Fun
email: colin at muffinlabs.com
description: > # this means to ignore newlines until "baseurl:"
  This is the help website for Before Dawn, an open source screensaver
  app. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://muffinista.github.io/before-dawn/" # the base hostname & protocol for your site
twitter_username: muffinista
github_username:  muffinista

# Build settings
markdown: kramdown
